Feature/new international plot
GenSpectrum/cov-spectrum-website pull request #110
Opened 2021-04-30 19:41 UTC by TKGZ

#90 #96 

![image](https://user-images.githubusercontent.com/36269621/116746400-b8126c80-a9fc-11eb-91fd-67e9a6c34f5b.png)
![image](https://user-images.githubusercontent.com/36269621/116746413-be084d80-a9fc-11eb-96d7-1b6eb406a74a.png)
![image](https://user-images.githubusercontent.com/36269621/116746465-cf515a00-a9fc-11eb-83a9-2fc7df29fc29.png)
![image](https://user-images.githubusercontent.com/36269621/116746469-d0828700-a9fc-11eb-9439-2955216a03f4.png)

- By default, shows currently selected country along with top 4 with most samples
- Switzerland always red, current country blue, others random
- Press x to clear all countries except currently selected country (which cannot be cleared)

2021-04-30 20:11 UTC, chaoran-chen requested changes

2021-04-30 20:11 UTC, chaoran-chen commented on src/widgets/VariantInternationalComparisonPlot.tsx
> +const colourStyles: Partial<Styles<any, true, any>> = {
I think that we used US English so far ;)

2021-04-30 20:11 UTC, chaoran-chen commented on src/widgets/VariantInternationalComparisonPlot.tsx
> +      count: entry[1]?.length,
I believe that's wrong. I think that entry[1] is a `ParsedMultiSample` that represents (potentially) multiple samples. Instead of using the length of the sample set, it is necessary to sum up `entry[1].count`

2021-04-30 20:11 UTC, chaoran-chen commented on src/widgets/VariantInternationalComparisonPlot.tsx
> +  }, [country]);
My editor says:

`ESLint: React Hook useEffect has a missing dependency: 'variantSamplesByCountry'. Either include it or remove the dependency array.(react-hooks/exhaustive-deps)`

Does it make sense?

2021-04-30 20:12 UTC, chaoran-chen commented
The layout and multi-filter are fantastic!!

2021-05-01 14:47 UTC, TKGZ commented
Restyled the hospital slightly (sorry for not doing in seperate issue)
![image](https://user-images.githubusercontent.com/36269621/116785997-d760d680-aa9c-11eb-9466-c35a499f45b0.png)

2021-05-01 16:26 UTC, merged