Github buttons
GenSpectrum/cov-spectrum-website pull request #121
Opened 2021-05-05 17:12 UTC by TKGZ

* about page
![image](https://user-images.githubusercontent.com/36269621/117181700-d0580200-add5-11eb-8c5e-7174ff72f6f4.png)

* left footer
![image](https://user-images.githubusercontent.com/36269621/117181726-d5b54c80-add5-11eb-8718-67344da6f5b4.png)

Could do some prettifications but we can do that later.

2021-05-05 17:13 UTC, TKGZ commented
We could consider putting it on the website header but that might be overkill

2021-05-05 18:01 UTC, chaoran-chen commented
Hi @TKGZ! Thanks for your work and I'm very sorry for not being clearer but I really only thought about including the small Github mark/icon (see below) and link it to our repository but having buttons for starring + watching seems too much for me. The purpose of the mark is to let everyone know that it is open source and give them a place to submit issues but I don't consider stars as very important.

![image](https://user-images.githubusercontent.com/18666552/117184208-c1bf1a00-add8-11eb-81ea-e03219e41d73.png)

2021-05-05 18:04 UTC, TKGZ commented
No worries this only took a few minutes, where do you think it should be put?

2021-05-05 18:11 UTC, chaoran-chen commented
hmm. top-right?

2021-05-06 14:22 UTC, TKGZ commented
@chaoran-chen I think it is okay to put it in the about page, and nowhere else: 
![image](https://user-images.githubusercontent.com/36269621/117314615-3c467300-ae87-11eb-90d0-db7305065d93.png)

2021-05-06 14:23 UTC, TKGZ commented
How about just keeping the small issue icon button, and removing the watch/star?

2021-05-06 14:23 UTC, TKGZ commented
![image](https://user-images.githubusercontent.com/36269621/117314779-60a24f80-ae87-11eb-80f5-b2a5341b61c6.png)

2021-05-06 14:24 UTC, TKGZ commented
and maybe replace it with the github icon? 
![image](https://user-images.githubusercontent.com/36269621/117314864-757ee300-ae87-11eb-81d1-bfa9f14cf69e.png)

2021-05-06 16:53 UTC, chaoran-chen commented
I think that's still too much. In my opinion, a simple mark is entirely sufficient.

2021-05-08 16:27 UTC, spacephoton commented
![image](https://user-images.githubusercontent.com/36269621/117546498-03470380-b02b-11eb-8514-03b0019173d9.png)
Small button only

2021-05-08 19:29 UTC, chaoran-chen requested changes
Thanks!

Please just remove the unused dependency. You can then merge :)

2021-05-08 19:29 UTC, chaoran-chen commented on package.json
> +    "@types/react-github-button": "^0.1.0",
I guess that we won't need this then?

2021-05-09 15:08 UTC, merged