basic touchable intensity
GenSpectrum/cov-spectrum-website pull request #180
Opened 2021-06-24 21:04 UTC by TKGZ

#178

@chaoran-chen before I continue, do you see any issues for intensity? 

I will probably have to change the way the tick is implemented since no longer using the index. Wasn't working so well anyway.

2021-06-24 21:10 UTC, TKGZ commented
Maybe also a good chance to simplify the implementation of the charts, I feel like they are unecessarily complex, and try to make them more reusable

2021-06-25 06:39 UTC, chaoran-chen commented
So far, it seems to work great, as long as we can bring the "changing ticks" back.

2021-06-29 15:17 UTC, TKGZ commented
@chaoran-chen can you have a look now? :)

2021-06-29 15:21 UTC, spacephoton commented
I also generalized part of the chart so they're easier to implement in future

2021-06-29 19:00 UTC, chaoran-chen requested changes
Hi @TKGZ! Works nicely and it's great to add a feature while reducing the amount of code!

Just one thing that I think should be improved:

![image](https://user-images.githubusercontent.com/18666552/123852567-bdb50180-d91c-11eb-8932-8e68eb14f58a.png)

This looks a little crowded and the whole at the end looks weird. Further, for consistency, it would be better to write the year with four digits.

2021-06-29 19:00 UTC, chaoran-chen commented on src/charts/Metrics.tsx
> +      <h3 id='chart-title' className='my-0 pb-4 pr-10 pt-0 text-gray-500'>
Why do we need to set an id?

Also a more general question: Shouldn't an id be unique in an HTML document and whenever we have multiple ChartAndMetrics loaded, wouldn't it be violated? Or does React have some kind of encapsulations in place?

2021-06-29 19:57 UTC, TKGZ commented on src/charts/Metrics.tsx
> +      <h3 id='chart-title' className='my-0 pb-4 pr-10 pt-0 text-gray-500'>
I actually don't know much about ID's, I just put them because they might be helpful later if we need to run pupeteer tests

2021-07-01 11:14 UTC, TKGZ commented
![CleanShot 2021-07-01 at 13 13 28](https://user-images.githubusercontent.com/36269621/124115528-311a5880-da6e-11eb-983c-1e7048698367.gif)
Couldn't find elegant way to adjust tick distance with custom ticks, so made the date appear only when it is active.

2021-07-01 11:24 UTC, merged