date picker issue
GenSpectrum/cov-spectrum-website pull request #477
Opened 2022-05-01 18:10 UTC by anastasia-escher

Added separate fields for start and end dates.

2022-05-01 19:38 UTC, chaoran-chen commented
Thanks @anastasia-escher!

@corneliusroemer, please check this out! Does this work well for you or do you have further suggestions?

2022-05-01 19:41 UTC, chaoran-chen requested changes
The mobile unfortunately is now even worse than before. The dropdown menu for the preset date ranges (All times, past 3 months, past 6 months, etc.) is now too small.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/18666552/166161937-b765ece0-0668-4ce4-9fc5-235db48f9201.png">

2022-05-02 17:20 UTC, corneliusroemer commented
Thanks @anastasia-escher and @chaoran-chen, that's great, now start and end dates can be typed!

Together with #485 this should resolve any date selection UX issues I'm having

2022-05-04 12:45 UTC, corneliusroemer commented
Hmm, now that I tested it, found a bug: If you type a date in the field and press enter, the new typed date is not accepted. One needs to click in the date picker, which shouldn't be necessary (I think)

2022-05-04 15:24 UTC, corneliusroemer commented
I think it's fixed by [0be1227](https://github.com/cevo-public/cov-spectrum-website/pull/477/commits/0be122754149643f28f8109538e54713c24ab421) now, thanks @anastasia-escher

2022-05-17 08:54 UTC, chaoran-chen commented
Hi. Sorry for the late response. Something is still wrong on my device. When I change the date with the date picker, it does not have any effect. Only when I choose the date with the date picker a second time, it works.

2022-05-17 14:01 UTC, anastasia-escher commented
Hi @chaoran-chen! And if you pick a date for the first time and press enter?

2022-06-01 16:12 UTC, anastasia-escher commented
@corneliusroemer , @chaoran-chen  please review

2022-06-02 11:18 UTC, corneliusroemer commented
@anastasia-escher thanks! There's a pretty big bug if you don't type a `-` after say `2022` but add a number, say typing `20223` in the date field.

As a result, the website goes completely white. Can you reproduce that? If not, I'm happy to give more details.

The usual UI flow for dates is that `-` are added automatically, maybe there's a material UI date field like that that could be used?

2022-06-15 14:31 UTC, anastasia-escher commented
@corneliusroemer , @chaoran-chen this is now a MUI version of the date picker, please check it out.

2022-06-16 08:34 UTC, chaoran-chen commented on package.json
> +    "@date-io/moment": "^2.14.0",
Hi @anastasia-escher. I will check out everything else later but already have a question: why are the above four dependencies needed?

2022-06-20 20:34 UTC, corneliusroemer commented
Looks really good @anastasia-escher!
I think it'd be good to switch the date format to ISO date like `2022-01-22` but that shouldn't be too hard I hope.

Really nice and reactive now, no need to press enter, easy to navigate with keyboard.

2022-06-22 14:23 UTC, chaoran-chen commented
@anastasia-escher, this looks good to me as well! Just like @corneliusroemer, I think that it would be better to use dates in the ISO format.

2022-06-23 09:02 UTC, chaoran-chen commented on src/components/DateRangePicker.tsx
> +              inputFormat='MM-dd-yyyy'
@anastasia-escher, ISO 8601 (https://www.iso.org/iso-8601-date-and-time-format.html) defines the date format as `yyyy-MM-dd` ;)

2022-06-23 09:03 UTC, chaoran-chen commented
Another thing: We used the package `react-datepicker` before. Can it now be removed?

2022-06-26 13:35 UTC, merged