add log scale
GenSpectrum/cov-spectrum-website pull request #534
Opened 2022-07-26 12:10 UTC by anastasia-escher

solves #462 

only log scale for now

2022-08-02 09:33 UTC, chaoran-chen requested changes
Hi @anastasia-escher, thanks for the PR! The absolute plot is not correct. When you check the log scale option and switch to the "absolute" numbers, the log scale checkbox disappears but it seems that it is still on and the y-axis is wrong:

![image](https://user-images.githubusercontent.com/18666552/182342338-1dddd6c1-fa80-4285-b49e-982debc6ae18.png)

2022-08-02 09:33 UTC, chaoran-chen commented on package.json
> +    "test": "craco test -u",
Please don't change the default behavior of the test command.

2022-09-15 20:40 UTC, chaoran-chen requested changes
If I switch to the "Absolute" view and then switch back to "Proportion", the plot looks like this:

![image](https://user-images.githubusercontent.com/18666552/190504452-22315a1c-1fc9-4482-852a-03d9047658fc.png)

(Observed in both Chrome and Firefox on Windows)

2022-09-16 09:08 UTC, chaoran-chen commented
Hmm.. this also isn't ideal... there is now a lot of empty space:

![image](https://user-images.githubusercontent.com/18666552/190601243-36ae9f6f-e53f-41b3-9a23-a68db11d7a56.png)

Why is the problem occurring?

2022-09-16 09:35 UTC, anastasia-escher commented
> Hmm.. this also isn't ideal... there is now a lot of empty space:
> 
> ![image](https://user-images.githubusercontent.com/18666552/190601243-36ae9f6f-e53f-41b3-9a23-a68db11d7a56.png)
> 
> Why is the problem occurring?

This has to do with the height of the plot wrapper and the margin-bottom of the plot... I'll try to make it look nicer.

2022-10-24 11:33 UTC, chaoran-chen requested changes
In the compare mode, the plot is now very small. The Log scale checkbox should be placed in the same row as the show CI button if there is sufficient space. There also shouldn't be so much empty space at to bottom.

![image](https://user-images.githubusercontent.com/18666552/197516257-1e3d7a66-3d19-4343-8b7b-fad1e375e34a.png)

2022-10-25 14:45 UTC, corneliusroemer commented
This is nice already, though as @chaoran-chen mentioned, the button could be placed in the same row as `absolute` etc
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/25161793/197805686-1763dd4a-66b5-46bc-a846-6f43602c44a0.png">

2022-10-27 08:09 UTC, chaoran-chen requested changes
The UI is unfortunately still not working properly.

On the mobile view, it's plot is still tiny:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/18666552/198227541-edfea1df-ff89-4aa6-81df-5091ee6aee55.png">

It introduced a lot of space under many plots. This is how the growth advantage plot looks on the production page:

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/18666552/198228218-6e2b2575-1842-4e3d-86e6-0194bd98c1bb.png">


This is how this PR looks like:

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/18666552/198227950-014b8e4a-4d53-43f2-b5ff-e73ad22f83ff.png">

2022-10-27 08:10 UTC, chaoran-chen commented
@dameyerdave, would you have the time to take a look and help out here?

2022-10-27 08:13 UTC, chaoran-chen commented on src/widgets/common.tsx
> +  margin-bottom: 70px;
This line looks problematic. The `ChartAndMetricsWrapper` is a widely used component. Is it a good idea to set such a fixed margin here?

2022-11-02 15:08 UTC, dameyerdave commented
Hi Chaoran, I totally missed you question. I'm very sorry for that. @anastasia-escher is on this and will solve this.

2022-11-14 10:12 UTC, chaoran-chen approved these changes
Thanks!

2022-11-14 10:12 UTC, merged