Improve structure of focus pages
GenSpectrum/cov-spectrum-website pull request #72
Opened 2021-03-25 17:40 UTC by tehwalris

This PR makes the major structural parts of the style changes that I presented at the last meeting:

  - Add cards around the things on the focus page
  - Move most of "Fitness advantange estimation" and "International comparison" to deep focus pages

Note that this PR on purpose does not make (most) cosmetic changes to the style (colors, shadows, etc). I'll do those in a future PR.

Please tell me if you notice any general issues or bugs with the restructured UI. I'm not really asking for technical feedback, since structural changes are tough to read in a PR.

2021-03-25 18:36 UTC, chaoran-chen requested changes
Could we give the age distribution plot a larger min-width? On my screen, the x-axis labels are not readable at all:

![image](https://user-images.githubusercontent.com/18666552/112525487-3a29c880-8da1-11eb-8695-3bc970491803.png)

Otherwise, it works great!

2021-03-29 11:16 UTC, TKGZ commented
Except for the sizing issue on large screens, I think it's ready for merge.
![image](https://user-images.githubusercontent.com/36269621/112829137-f7ae0780-9090-11eb-89ba-42284fedaed3.png)

2021-03-29 11:47 UTC, TKGZ commented
Shall we just put these on two rows instead of one? 
There isn't much advantage in keeping on same row

![Uploading image.png…]()

2021-03-31 21:03 UTC, tehwalris commented
I limited the layout to at most 2 columns, even on large screens. I also made the sequences over time and demographics plots have an equal width, as @TKGZ once suggested. Here's how that looks on my screen:

![full-screen](https://user-images.githubusercontent.com/1489115/113210443-84fd8180-9274-11eb-8fa5-b7bd87bab7e4.png)

I increased the minimum width required for the demographics plot to be split, but that wasn't enough to stop the labels from overlapping. I tried hiding the labels when there isn't enough space, but that looks really bad. In the end I chose to show a shorter form of labels when the plot is narrow. Here they are at the smallest width which the demographics plot can have in a two-column layout:

![smallest-two-column-width](https://user-images.githubusercontent.com/1489115/113210720-d6a60c00-9274-11eb-83bc-47dcca2430f4.png)

The smallest width at which full labels are still used looks like this:

![smallest-full-label-width](https://user-images.githubusercontent.com/1489115/113211039-3ac8d000-9275-11eb-9418-c5d5f64d3036.png)

2021-03-31 21:04 UTC, merged

2021-03-31 21:10 UTC, tehwalris commented
I forgot to push commit 69781fb8864beee40c35e7c8dbc54c2ffc74a7d1 before merging this PR. I merged it to `develop` separately.

2021-03-31 21:26 UTC, TKGZ commented
Awesome seems great!