Chat: Improve results tables
GenSpectrum/cov-spectrum-website pull request #782
Opened 2023-04-18 05:04 UTC by JonasKellerer

Resolves #778

2023-04-18 05:06 UTC, JonasKellerer commented
'Check the UI/UX on mobile and improve if needed' is still open. I checked it through the browser tools, where it seems okay. I think not needing to scroll due to the pages helps. Feedback is very welcome.

2023-04-18 15:15 UTC, chaoran-chen requested changes
Thank you very much! Only one small request (see below), otherwise it's perfect!

2023-04-18 15:15 UTC, chaoran-chen commented on src/components/chat/IncomingResponseMessage.tsx
> +        slots={{ toolbar: CustomToolbar }}
I think that it would be better to save some space and make the rows as narrow as possible

2023-04-18 15:21 UTC, chaoran-chen commented
Oh, and I don't think that we need the "print" option. Let's only offer the CSV download for now.

2023-04-19 08:38 UTC, chaoran-chen approved these changes

2023-04-19 08:43 UTC, merged