Nucleotide Diversity
GenSpectrum/cov-spectrum-website pull request #784
Opened 2023-04-21 14:20 UTC by philipschulz

- Nucleotide Diversity chart component for Focus page
- Nucleotide Diversity multi chart component for CompareEquals page

2023-04-25 14:24 UTC, fengelniederhammer requested changes
Please check the code for unnecessary things: There are a couple of fragments, variables and other things that we could get rid of.

Also I would propose to restructure the code:
* create a folder `/src/components/NucleotideEntropy`
* In that folder, create an `index.tsx` that exposes `NucleotideEntropy` and `NucleotideEntropyMultiChart` (either by reexport or by holding the actual implementation). That way, consumers only ever need to know that index.tsx and no other file in the folder.
* Hooks go into separate files in that folder.
* Also extract components into separate files: Either if they are large by themselves, or if they can be reused by multiple other components.
* In general methods should not be longer than 100 lines. Files should also not be much longer than that either.

Also please add unit tests to make sure that your code actually works. In the ideal case, you can split your tests into display and logic tests:
* test the hooks separately. This is where the logic sits. Make sure that the computation is correct. "Given the server returns some specific data, then the hooks computes xyz...".
* test the components separately. Mock the hooks. "Given some specific data to display, then the component shows..."

Also please try to get rid of most of the comments in the code. Comments tend to be outdated and get misplaced, because people forget to update them when changing the code. Some few comments might be justified, but usually one can apply any of:
* The code is already expressive enough and the comment only paraphrases what's written in the code. In that case, simply delete the comment.
* The code explains what's going on in the code. It also paraphrases the code, but the code is more complex, so that it deserves some explanation. In that case, extract the code into a class/method/component (whatever fits) and give it a name such that you don't need the comment, because it's included in the name.

And please use expressive names for all variables. It really helps other people to understand the code a lot faster, if names communicate the purpose of variables.

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +type Variant = {
Do we need this type? According to my IDE it is unused.

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
eslint (`npx eslint .`) complains about a couple of lines here and in `NucleotideEntropy.tsx`. Could you please fix those?

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +                { label: 'AA', value: 'aa' },
The surrounding diagrams use the full names.
```suggestion
                { label: 'Nucleotides', value: 'nuc' },
                { label: 'Amino acids', value: 'aa' },
```

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
Please use prettier to format the files. If you use IntelliJ, there is a nice plugin :)

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +    const [deletions, setDeletions] = useState<boolean>(false);
```suggestion
    const [includeDeletions, setIncludeDeletions] = useState<boolean>(false);
```
That would make it more obvious that the variable is a boolean.

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +    if (variants![0].length == 0) {
That `!` looks supsicious to me. This basically disables typesafety. Why is the type nullable if you seem to be sure that it is not null here?

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +          {/* AA vs. nucs */}
Do we need those comments here? I'd propose to
* either simply delete them
* or extract the code that the comment refers to into a separate component and give that component a name that replaces the comment.

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +          {
I think we don't need this pair of brackets, do we?

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +                onChange={ev => setGene(ev.target.value)}
What is `ev`? Could you please give it a proper name? :)

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +      const dayArray: UnifiedDay[] = [selectors[0].dateRange?.getDateRange().dateFrom!, selectors[0].dateRange?.getDateRange().dateTo!];
Explicit type declarations are usually not necessary. Typescript is smart enough to figure out the type by itself.
```suggestion
      const days = [selectors[0].dateRange?.getDateRange().dateFrom!, selectors[0].dateRange?.getDateRange().dateTo!];
```

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +      }
Using `Array.map` is usually more idiomatic are easier to read:
```suggestion
      const weekDateRanges: DateRange[] = globalDateCache
        .weeksFromRange({
          min: dayRange.min.isoWeek,
          max: dayRange.max.isoWeek,
        })
        .map(week => ({
          dateFrom: week.firstDay,
          dateTo: week.firstDay,
        }));
```

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +  const data = useMemo(() => {
This could be inlined:
```suggestion
  return useMemo(() => {
```

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +      })
Same here: (Leveraging ChatGPT :) )
```suggestion
        const weekSelectors = selectors.flatMap(selector =>
            weekDateRanges.map(w => ({
                ...selector,
                dateRange: new FixedDateRangeSelector(w),
            })),
        );
```

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +      })
This is the explanation that ChatGPT gave:
This version leverages the flatMap function to flatten the resulting nested arrays into a single-level array while applying the provided mapping function. In this case, for each selector element, we create a new array of LapisSelector objects with the updated dateRange property, and then flatten the resulting arrays into one continuous array.

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +    if (variants![0].length == 0) {
Could you please double check all the `!` in your code? This potentially results in errors.

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +          weekSelectors.map((w, i) =>
Let's also use proper variable names here, please: 
```suggestion
          weekSelectors.map((weekSelector, i) =>
```

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +              const proportions: MutationProportionEntry[] = data.payload.map(m => m);
Why do we need this line? It essentially does nothing.

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +  const weeklyVariantMutationProportionQuery = useQuery(
Let's also get rid of the comments here: :) 
```suggestion
  const weeklyVariantMutationProportions = useProportionsPerPositionInWeeklySegments(selectors, sequenceType);

```

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +    if (!sequenceType) {
Can `sequenceType` ever be falsy?

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +        sequenceType: sequenceType,
Why do you return `sequenceType` here? This is the same as the input.

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +      return undefined;
Why return undefined in this case? Isn't this rather an error? Is it important to check this here?

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +    const dayArray = Array.from(dayMap.values()).slice(0, -1); //depending on the day, the latest week just started, so the entropy is calculated as 0 because there are no samples
Also according to ChatGPT, this can be simplified to this:
```suggestion
const dayMap = timeData.reduce((map, tt) => {
  const day = tt.day;
  const dayGroup = map[day] || {};
  return {
    ...map,
    [day]: { ...dayGroup, ...tt }
  };
}, {});

const dayArray = Object.values(dayMap).slice(0, -1);
```

Maybe we can also improve the naming of variables here? `tt` should be something understandable, also including `Map` or `Array` usually has no benefit in readability. `Map` can usually be replaced by something like `daysGroupedBy<keys>`. Instead of `Array`, you can simply use the plural (here `days`).

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +    <>
I think we don't need this fragment, do we?

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropy.tsx
> +  const [plotType, setPlotType] = useState<string>('time');
I think we can improve the typing (and naming) here:
```suggestion
  const [plotType, setPlotType] = useState<'time' | 'position'>('time');
```

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropy.tsx
> +    <>
This also looks like we don't need that fragment.

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropy.tsx
> +      <div className='mb-2 flex'>
I would guess that we could extract some of those components to reuse them here and in `NucleotideEntropyMultiChart`

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropy.tsx
> +          .reduce((x, a) => x + a, 0);
This is very hard to read. Could you maybe extract parts of it?

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropy.tsx
> +const CalculateEntropy = (
This should have a name starting with lower case. Only React components should start with a capital letter.

2023-04-25 14:24 UTC, fengelniederhammer commented on src/components/NucleotideEntropy.tsx
> +  positionGroups.map(p => {
Either use `forEach` or return something from the array function in `map`, please.

2023-04-25 14:30 UTC, fengelniederhammer commented on src/components/NucleotideEntropyMultiChart.tsx
> +  return Object.entries(obj).filter(([key, value]) => value !== undefined).map(([key, value]) => value).toString();
Calling unused variables `_` is a common pattern, if you somehow have to include them, but you don't actually need them:
```suggestion
  return Object.entries(obj).filter(([_, value]) => value !== undefined).map(([_, value]) => value).toString();
```

2023-04-25 14:34 UTC, fengelniederhammer commented
You might also want to rebase your branch to the current develop branch. It's quite a few commits behind. :)

2023-05-17 07:09 UTC, fengelniederhammer commented on src/components/NucleotideEntropy/NucleotideEntropyMultiChart.tsx
> +  const variants = (exploreUrl.variants ?? []).map(nonNullValuesToString);
@chaoran-chen Does this particular line make sense? I'm not so sure about it. It seems to work, but it might be quite fragile.

2023-05-17 07:30 UTC, fengelniederhammer approved these changes
From my side it looks good now, but it would be good if someone else could double check my refactorings ;)

2023-06-01 13:44 UTC, chaoran-chen requested changes
By default, the positions with zero entropy should be included. In fact, I think that we should negate the checkbox to "Exclude positions with zero entropy"

![image](https://github.com/GenSpectrum/cov-spectrum-website/assets/18666552/e06bc897-455a-402f-918f-10623f650242)

Unfortunately, I see that the plot has some performance issues when the positions with zero entropy are included: It takes a long time to load and the zooming is very slow. @fengelniederhammer , do you see a way to improve the performance?

2023-06-07 09:07 UTC, fengelniederhammer commented
I'm not sure whether we can do something here. It think it just takes the browser very long to render 30.000 bars. 

The computation is clearly not the problem: When changing the threshold from 0.1 to 0, the data is the same (cached by useMemo). The browser just has to rerender the plot.

Why is it actually useful to see mostly empty bars?

2023-06-08 11:07 UTC, chaoran-chen commented
If we exclude the zero entropy bars, the x-axis is not "uniform" anymore. It jumps from 2 to 12, etc.

![image](https://github.com/GenSpectrum/cov-spectrum-website/assets/18666552/a80402d1-d2a6-46f8-9cf5-e9d487fdd684)

Would it be possible to not actually render the zero entropy positions but just leave the space empty?

2023-06-16 11:47 UTC, chaoran-chen approved these changes
As further performance improvements seem difficult at the moment, I'll merge it.

Thank you very much, @philipschulz and @fengelniederhammer for the great work!

2023-06-16 11:48 UTC, merged