Swiss curves page text update
GenSpectrum/cov-spectrum-website pull request #812
Opened 2023-06-07 06:31 UTC by JonasKellerer

Resolves #800

2023-06-07 06:32 UTC, JonasKellerer commented
I added the relevant text, but we could discus about the design :)

2023-06-07 07:04 UTC, chaoran-chen requested changes
There are a few more links that should be added. They are in the document as comments which you couldn't see as a guest:

<img src="https://github.com/GenSpectrum/cov-spectrum-website/assets/18666552/af256fe3-3bb5-43fd-ad9c-fd15084db399" width="300" />

I added the links in the comments in code

2023-06-07 07:04 UTC, chaoran-chen commented on src/models/wasteWater/story/WasteWaterStoryPage.tsx
> +      <h3>Computational Biology Group (CBG) ETH Zürich / Swiss Institute of Bioinformatics</h3>
"Computational Biology Group (CBG) ETH Zürich" should point to https://bsse.ethz.ch/cbg

"Swiss Institute of Bioinformatics" should point to https://www.sib.swiss/niko-beerenwinkel-group

2023-06-07 07:04 UTC, chaoran-chen commented on src/models/wasteWater/story/WasteWaterStoryPage.tsx
> +      <h3>Computational Evolution (cEvo) ETH Zürich / Swiss Institute of Bioinformatics</h3>
"Computational Evolution (cEvo) ETH Zürich" should point to https://bsse.ethz.ch/cevo

"Swiss Institute of Bioinformatics" should point to https://www.sib.swiss/tanja-stadler-group

2023-06-07 07:04 UTC, chaoran-chen commented on src/models/wasteWater/story/WasteWaterStoryPage.tsx
> +        , ETH Zürich / Swiss Institute of Bioinformatics
"Swiss Institute of Bioinformatics" should point to https://www.sib.swiss/daniel-stekhoven-group

2023-06-07 07:05 UTC, chaoran-chen commented
@mcarrara-bioinfo, what do you think? Please let us know if this is as you expected!

2023-06-08 13:28 UTC, mcarrara-bioinfo commented
> @mcarrara-bioinfo, what do you think? Please let us know if this is as you expected!

@chaoran-chen The preview does not work for me. The page itself loads, but it hangs on loading the actual content, leaving only header, footer and loading animation. I left it for 10 minutes and saw no change. Do I need a Vercel account to access?

2023-06-08 13:30 UTC, chaoran-chen commented
Hi @mcarrara-bioinfo, sorry, CoV-Spectrum was down for 30 minutes and is just back. Can you please try again?

2023-06-12 16:43 UTC, mcarrara-bioinfo commented
> Hi @mcarrara-bioinfo, sorry, CoV-Spectrum was down for 30 minutes and is just back. Can you please try again?
@chaoran-chen thank you, after your message I tried again and it worked.

Dear all, both CBG and NEXUS reviewed the preview and everything is approved as-is. As far as we are concerned, you have greenlight to deploy the changes as soon as you see fit.

Thank you for your efforts.

2023-06-13 12:45 UTC, merged